### ISSUE TITLE
server replied: Forbidden

### ISSUE THREAD

**Issue by boxledev** [JarbasSkills/skill-natgeo-pod#1]
Hi,
I just tried the skill and I just a get a black screen and the following error on the gui:
`Error transferring https://www.nationalgeographic.com/content/dam/photography/photo-of-the-day/2020/07/pod-03-07-2020_nationalgeographic_23818.jpg - server replied: Forbidden`
on the cli I get:
`  File "/opt/mycroft/skills/skill-natgeo-pod.jarbasskills/__init__.py", line 23, in update_picture
    data = requests.get(url).json()
  File "/home/dm/mycroft-core/.venv/lib/python3.8/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)
`

**Comment by JarbasAl** [comment]
moved to https://www.natgeotv.com/ca/photo-of-the-day and should work again
